# Generated by Django 5.2.13 on 2026-05-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('head_branch', models.CharField(max_length=255)),
                ('github_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'unique_together': {('repository', 'github_pr_number')},
            },
        ),
    ]
